; ZAD1-KV3
; Napišite program za igru najbrži prst
; sa 4 igrača. Na stisak tipke ispišite
; broj od 1 do 4 te pozovite funkciju 
; DELAY500 tako da prođe 10 s.

ADDRESS 000
START:	INPUT S0, BTN_PORT
		LOAD S1, 00
PLAYER:	RR S0
		JUMP Z, ISPIS
		ADD S1, 01
		JUMP PLAYER
ISPIS:	OUTPUT S1, HEX1_PORT
		LOAD S2, 20
DELAY:	CALL DELAY500
		SUB S2, 01
		COMPARE S2, 00
		JUMP Z, START
		JUMP DELAY
DELAY500: 	LOAD SA, 00
PETLJA1: 	LOAD SB, 00
PETLJA2:	LOAD SC, BE
PETLJA3: 	SUB SC, 01
		JUMP NZ, PETLJA3
		SUB SB, 01
		JUMP NZ, PETLJA2
		SUB SA, 01
		JUMP NZ, PETLJA1
		RETURN

; ZAD2-KV3
; Na pojavu interrupta prebrojite koliko
; je sklopki sa oba SW porta postavljeno u 1.
; Rezultat spremite u memoriju i ispišite na HEX.

ADDRESS 000
ENABLE INTERRUPT
START:	JUMP START
ISR:		INPUT S1, SW1_PORT
		INPUT S2, SW2_PORT
		LOAD S3, 00
PETLJA1:	RR S1
		JUMP Z, PETLJA2
		ADDCY S3, 01
		JUMP PETLJA1
PETLJA2:	RR S2
		JUMP Z, ISPIS
		ADDCY S3, 01
		JUMP PETLJA2
ISPIS:	OUTPUT S3, HEX1_PORT
		STORE S3, 00
		RETURNI ENABLE
ADDRESS 7FF
JUMP ISR

; ZAD3-KV3
; Napravite igraću kocku u asembleru.
; PicoBlaze treba mijenjati broj od 1 do 6
; i na pojavu interrupta treba ispisati
; broj na HEX pokazniku.

ADDRESS 000
ENABLE INTERRUPT
LOAD S0, 01
START:	CALL DELAY500
		COMPARE S0, 06
		JUMP Z, RESET
		ADD S0, 01
		JUMP START
RESET:	LOAD S0, 01
		JUMP START
DELAY500: 	LOAD SA, 00
PETLJA1: 	LOAD SB, 00
PETLJA2: 	LOAD SC, BE
PETLJA3: 	SUB SC, 01
		JUMP NZ, PETLJA3
		SUB SB, 01
		JUMP NZ, PETLJA2
		SUB SA, 01
		JUMP NZ, PETLJA1
		RETURN
ISR:		OUTPUT S0, HEX1_PORT
RETURNI ENABLE
ADDRESS 7FF
JUMP ISR

; ZAD4-KV3
; Pronađite najmanji i najveći broj među
; 16 brojeva u memoriji te ih ispišite
; na HEX pokaznike.

ADDRESS 000
ENABLE INTERRUPT
LOAD S0, 0F
LOAD S1, 00
UNOS:		STORE S0, (S1)
		COMPARE S0, 00
		JUMP Z, START
		SUB S0, 01
		ADD S1, 01
		JUMP UNOS
START:	LOAD S0, 00 ; ADRESA SCRATCHPADA
		LOAD S1, 0F ; MIN
		LOAD S2, 00 ; MAX
		LOAD S3, 00 ; TEMP
UVOZ:		FETCH S3, (S0)
LESSTHAN:	COMPARE S3, S1
		JUMP NC, MORETHAN
		LOAD S1, S3
MORETHAN:	COMPARE S2, S3
		JUMP NC, NEXT
		LOAD S2, S3
NEXT:		COMPARE S0, 0F
		JUMP Z, ISPIS
		ADD S0, 01
		JUMP UVOZ
ISPIS:	OUTPUT S1, HEX1_PORT
		OUTPUT S2, HEX2_PORT
		JUMP START
